# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XMA2D4Zf-ME-w0kVQGn_9vWEf4mV_By5
"""

# prompt: open the out_plot file and readline not the first all the other
import numpy as np
import matplotlib.pyplot as plt
import sys

uuioo=sys.argv[1]
vv=int(input("number of point?"))
uu=vv+1
nombre=uu+1
data=[0]*nombre
value=[0]*nombre
gamma=np.zeros(2*vv+1)
IV_0=np.zeros(2*vv+1)
IH_0=np.zeros(2*vv+1)
IV_90=np.zeros(2*vv+1)
IH_90=np.zeros(2*vv+1)
    
for i in range(1,uu+1):
    with open('out_plot','r') as f:
        data[i-1]=f.readlines()[i]
        value[i-1] = data[i-1].split()
        gamma[i-1]=float(value[i-1][0])
        IH_0[i-1]=float(value[i-1][1])
        IH_90[i-1]=float(value[i-1][2])
        IV_0[i-1]=float(value[i-1][3])
        IV_90[i-1]=float(value[i-1][4])
        


kkkk=0

for i in range(uu,2*vv+1):
    kkkk+=1
    gamma[i]=-gamma[vv-kkkk]
    IH_0[i]=IH_0[vv-kkkk]
    IH_90[i]=IH_90[vv-kkkk]    
    IV_0[i]=IV_0[vv-kkkk]
    IV_90[i]=IV_90[vv-kkkk]
    

plt.plot(gamma,IV_0,label='IV_0')
plt.plot(gamma,IV_90,label='IV_90')
plt.plot(gamma,IH_0,label='IH_0')
plt.plot(gamma,IH_90,label='IH_90')
plt.legend()
plt.xlabel('angle')
plt.ylabel('SHS Intensity')
plt.savefig(uuioo)
plt.show()


