# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XMA2D4Zf-ME-w0kVQGn_9vWEf4mV_By5
"""

# prompt: open the out_plot file and readline not the first all the other
import numpy as np
import matplotlib.pyplot as plt
import sys

uu=sys.argv[1]

nombre=100
data=[0]*nombre
value=[0]*nombre
gamma=np.zeros(100)
IV=np.zeros(100)
IH=np.zeros(100)
for i in range(1,101):
    with open('out_plot','r') as f:
        data[i-1]=f.readlines()[i]
        #print(data[i-1])
        value[i-1] = data[i-1].split()
        #print(value[i-1])
        gamma[i-1]=float(value[i-1][0])
        IV[i-1]=float(value[i-1][1])
        IH[i-1]=float(value[i-1][2])

plt.plot(gamma,IV,label='IV')
plt.plot(gamma,IH,label='IH')
plt.legend()
plt.xlabel('Gamma')
plt.ylabel('SHS Intensity')
plt.savefig(uu)
plt.show()
